-- Migration 072: Restore draw_code column to draws table
-- ─────────────────────────────────────────────────────────────────────────────
-- BACKGROUND
-- ----------
-- Migration 016 created the draws table with a draw_code TEXT UNIQUE NOT NULL
-- column (format: DRAW-YYYYMMDD-XXXX). This column is used by draw_service.go
-- for idempotency, external referencing, and admin display.
--
-- Migration 021 (passport_badges_and_wars) re-created the draws table using
-- CREATE TABLE IF NOT EXISTS, which preserved the existing table but the new
-- definition omitted draw_code. Since the table already existed (from migration
-- 016), Postgres kept the old schema — but migration 060 (ensure_critical_tables)
-- also re-created draws without draw_code, which means on a fresh database
-- (where migration 060 runs before 016's table exists) draw_code is missing.
--
-- This migration ensures draw_code exists on all environments.
--
-- CHANGES
-- -------
--   1. Add draw_code TEXT column if it does not exist (safe on existing DBs).
--   2. Back-fill any existing rows with a generated code so NOT NULL is safe.
--   3. Add NOT NULL constraint after back-fill.
--   4. Add UNIQUE index.
--
-- NOTE: The application generates codes in the format DRAW-YYYYMMDD-XXXX.
--       Back-filled codes use DRAW-LEGACY-{id_prefix} to distinguish them.
-- ─────────────────────────────────────────────────────────────────────────────

-- Step 1: Add draw_code as nullable first (safe if it already exists)
ALTER TABLE draws
    ADD COLUMN IF NOT EXISTS draw_code TEXT;

-- Step 2: Back-fill any rows that have a NULL draw_code so we can add NOT NULL.
-- Uses the draw id prefix to create a unique deterministic code.
UPDATE draws
SET draw_code = 'DRAW-LEGACY-' || UPPER(SUBSTRING(id::text, 1, 8))
WHERE draw_code IS NULL OR draw_code = '';

-- Step 3: Now enforce NOT NULL (safe because all rows are back-filled)
ALTER TABLE draws
    ALTER COLUMN draw_code SET NOT NULL;

-- Step 4: Add unique index (idempotent)
CREATE UNIQUE INDEX IF NOT EXISTS uidx_draws_draw_code ON draws (draw_code);

COMMENT ON COLUMN draws.draw_code IS
    'Human-readable unique code for this draw, e.g. DRAW-20260101-1234. '
    'Generated by draw_service.go:generateDrawCode(). Used for external references and admin display.';
