-- Migration 085: Add Video Story Builder (multi-scene image-to-video) tool
-- Uses FAL.ai fal-ai/kling-video/v1.6/standard/multi-image-to-video
-- Supports up to 4 images, each with its own scene description
INSERT INTO studio_tools (
    id,
    name,
    slug,
    description,
    category,
    point_cost,
    provider,
    provider_tool,
    is_active,
    is_free,
    icon,
    sort_order,
    entry_point_cost,
    ui_template,
    ui_config,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'Video Story Builder',
    'video-story',
    'Upload up to 4 images and describe each scene — AI weaves them into a single cinematic video with smooth transitions.',
    'Create',
    800,
    'fal',
    'fal-ai/kling-video/v1.6/standard/multi-image-to-video',
    true,
    false,
    '🎬',
    55,
    200,
    'video-multi-scene',
    '{
        "show_multi_image": true,
        "max_images": 4,
        "show_duration": true,
        "duration_options": [5, 10],
        "show_aspect_ratio": true,
        "aspect_ratio_options": ["16:9", "9:16", "1:1"],
        "show_motion_style": false,
        "show_motion_intensity": false,
        "show_audio_toggle": false,
        "show_end_image": false,
        "placeholder_prompt": "Describe the overall story or mood of the video...",
        "submit_label": "Build Story Video \u2192"
    }'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO UPDATE SET
    name             = EXCLUDED.name,
    description      = EXCLUDED.description,
    category         = EXCLUDED.category,
    point_cost       = EXCLUDED.point_cost,
    provider         = EXCLUDED.provider,
    provider_tool    = EXCLUDED.provider_tool,
    is_active        = EXCLUDED.is_active,
    icon             = EXCLUDED.icon,
    sort_order       = EXCLUDED.sort_order,
    entry_point_cost = EXCLUDED.entry_point_cost,
    ui_template      = EXCLUDED.ui_template,
    ui_config        = EXCLUDED.ui_config,
    updated_at       = NOW();
